name: Auto-merge

on: [check_run]
jobs:

  automerge:
    runs-on: ubuntu-latest
    steps:
      - name: Automerge
        needs: build
        uses: pascalgn/automerge-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}